apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frontend"
  labels:
    app: perplexica-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perplexica-frontend
  template:
    metadata:
      labels:
        app: perplexica-frontend
    spec:
      containers:
      - name: perplexica-frontend
        image: "{{ .Values.perplexica.frontend.image.repository }}:{{ .Values.perplexica.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.perplexica.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.perplexica.frontend.service.port }}
        env:
        - name: NEXT_PUBLIC_API_URL
          value: {{ .Values.perplexica.config.nextPublicApiUrl }}
        - name: NEXT_PUBLIC_WS_URL
          value: {{ .Values.perplexica.config.nextPublicWsUrl }}
