{{- if .Values.searxng.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-searxng-pvc"
spec:
  accessModes:
    - {{ .Values.searxng.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.searxng.persistence.size }}
  storageClassName: {{ .Values.searxng.persistence.storageClass }}
{{- end }}
