apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
type: Opaque
stringData:
  # Add your sensitive keys here
  # For example:
  # API_KEY: "your-api-key"
  # DB_PASSWORD: "your-db-password"
